luvit/lit

.gitignore, alias.sh, dev.fish, lib/README, lib/core.lua, lib/db.lua, lib/pkg.lua, lib/vfs.lua, package.lua, web-install.ps1, web-install.sh
Now commands like `lit make`, `lit add` can work on zip files and treat them as readable directories.
=> Add zipfile support to reading APIs in core

libs/db.lua
If you run the fs_scandir in a directory placed on a virtual shared folder (I'm using vagrant), fs_scandir does not return the *direntry* type. **The problem is on the libuv, uv_fs_scandir_next**
The file db.lua throws an error because the type is nil:
error("Unsupported type at " .. path .. ": " .. tostring(stat.type))
Here is some test using coro-fs.scan_dir:
```
local uv = require('uv')
require('luvi').bundle.register("luvit-require", "deps/require.lua")
local require = require('luvit-require')("bundle:main.lua")
local fs = require('coro-fs')
_G.p = require('pretty-print').prettyPrint
coroutine.wrap(function() 
for entry in assert(fs.scandir(".")) do
p(entry)
end
end)()
```
**Result ran in a directory not shared**
```
vagrant@vagrant-ubuntu-trusty-32:~/luviapp$ LUVI_APP=. …
```
=> fs_scandir does not always returns the direntry type. I've changed the db.lua for a quick fix without breaking anything else

commands/update.lua
* Mirrors logic in libs/core.lua's realMake fn
=> Fix update on Windows not targetting .exe files

libs/core.lua
This compiles all lua files when building a luvi app zip.  The final zip file isn't always smaller, but it uses a bit less ram.  Also authors can write verbose comments now without worrying about it hurting their luvi app.
=> Compile Lua files when making luvi app

deps/coro-tcp.lua
I hope print EADDRINUSE: address already in use
this patch isn't good?   or return error?
=> hasn't output any message while tcp port is already used

deps/coro-http.lua
`not (contentLength and chunked)` is true when contentLength has a value.
`not (true and false) == true`.
it causes the content-length headers to be sent across twice, which is an issue with some services.
=> content length header should only be sent once if specified in the list of headers.

libs/rules.lua
* Closes #111 
I also cleaned up the variable names a bit, or I tried to. I may have gotten some stuff wrong, so let me know if I misinterpreted anything.
Output before:
```
compiling filter: C:\test/** includes by default (first rule is negative)
including: include.lua
including: nest\test.lua
including: package.lua
skipping: test
skipping: tests
```
Output after:
```
compiling filter: C:\test/** includes by default (first rule is negative)
including: extra.txt
including: include.lua
including: nest\test.lua
including: nest\test.txt
including: package.lua
skipping: test
skipping: tests
```
=> Fix files included by default not showing up in the log

libs/api.lua, libs/core.lua, libs/pkg.lua
This is a new behavior in lit.
When you add a new package to the database using `lit add` that contains dependencies and is a tree, lit will calculate the current set of dependencies for that package and save this snapshot hash along with the metadata stored in the git tag.
Then when using `lit make` with a `lit://foo/bar` url or using the `.zip` generator in the web API, the snapshot will be used to generate the zip file instead of the current set of dependencies.
This means that top-level apps will freeze all their deep dependencies at time of publish.  If an app wants to pick up big fixes in deep dependencies it will need to publish a new version.  A new build version would be enough.
But this also means that foo/bar/v1.2.3 will *always* have the same exact content and not change over …
=> Snapshot feature so published lit apps have reproducible builds

README.md
I forgot to add the `lit init` command to the README
=> add lit init description to readme

commands/auth.lua, commands/init.lua
* Use %HOMEDRIVE% env var to get the correct drive, as %HOMEPATH% only contains the drive-relative path.
* Example: %HOMEDRIVE% contains "C:", %HOMEPATH% contains "\Users\username". Putting them together gets you to full absolute path
* More info: http://stackoverflow.com/a/2115116
=> Fix .gitconfig not being found on Windows when cwd is not on the home drive

README.md
Uniaika from the IRC was having an issue where lit didn't have the git submodule. The instructions don't quite work as they are.
=> git clone should be recursive so that the git submodule is pulled down.

libs/README, libs/api.lua
- Gets the metadata or the zip bundle of the latest version of the package
- See #161
---
No clue if this is the optimal solution, but I figured I'd offer it as a PR just in case. Note also this makes the version parameter in the API a bit more flexible: both `/packages/author/name/v1.0.0` and `/packages/author/name/1.0.0` will work now (whereas before, the preceding `v` was required).
=> API: Add /packages/$AUTHOR/$TAG/latest and /packages/$AUTHOR/$TAG/latest.zip

README.md
- Fix for deps/git not being present in the Github zip
Closes #161
=> Use latest lit package when building from source

libs/api.lua
To access, hit the /metrics endpoint of the Lit server.  This will produce a
plain text, machine-readable result informing the user of the total memory
consumed by the Lit server, as well as the total number of file descriptors
used by Lit at the time the metrics were requested.
=> Add memory and file descriptor metrics to Lit server.

libs/core.lua
See luvit/luvit#882
Will now give the following error instead:
```
fail: [string "bundle:libs/core.lua"]:133: Malformed package metadata. Package name must be of the format 'author/package'.
```
Note that malformed (or missing) version errors are already handled by semver.normalize within pkg.normalize.
=> Better error message when package name is malformed

libs/get-installed.lua, libs/pkg.lua
Closes #184. Tested and working, see https://travis-ci.org/squeek502/luvit/jobs/140012772 (no dependencies fetched from remote)
f57e2a4 is needed because the lit deps were also being fetched on Travis and locally on my Windows machine. Here's an example build without that fix included: https://travis-ci.org/squeek502/luvit/jobs/140010976
Let me know if the solutions can be improved.
=> Fix local deps not being used consistently

luvit-loader.lua
Fixes for some some issues I ran into while making [luver](https://github.com/squeek502/luver).
Let me know if you'd like any more information about any of the changes or if you see a better way to handle any of these issues.
=> Some luvit-loader fixes/improvements

deps/coro-net.lua, deps/secure-socket/biowrap.lua, deps/secure-socket/init.lua
luvit/lit#212
luvit/luvit#986
luvit/luvit#987
=> Adds missing hostname to ssl handle

deps/coro-websocket.lua, deps/coro-wrapper.lua
The WebSocket standard describes a close frame, where a final message may be present.
```
5.5.1.  Close
The Close frame contains an opcode of 0x8.
The Close frame MAY contain a body (the "Application data" portion of
the frame) that indicates a reason for closing, such as an endpoint
shutting down, an endpoint having received a frame too large, or an
endpoint having received a frame that does not conform to the format
expected by the endpoint.  If there is a body, the first two bytes of
the body MUST be a 2-byte unsigned integer (in network byte order)
representing a status code with value /code/ defined in Section 7.4.
Following the 2-byte integer, the body MAY contain UTF-8-encoded data
with value /reason/, the interpretation of which is not defined by
this specification.  This data is …
```
=> WebSocket close frame and empty buffer returns

deps/websocket-codec.lua
In #211, I replaced each `#chuck` with `length`. Apparently this line should have remained the same. The only reason why `length` can be used in the other two checks is because `length < n` is equivalent `#chunk < start + n`. Sorry for the confusion.
=> Fixes WebSocket chunk length check

deps/coro-spawn.lua, libs/exec.lua
- coro-spawn will now return nil and the error message when uv.spawn errors
- exec will also return nil and the error message when coro-spawn errors
- fixes #219
=> Fix coro-spawn hanging when uv.spawn returns an error

deps/coro-http.lua
Re: #216
`coro-net.connect` supports timeouts, so this is just a matter of passing the argument along from `coro-http.request`. There's no request handle like there is with luvit, so I guess this is the best way to do it.
=> Adds support for http request timeout

deps/http-codec.lua
Example: "X-Geo-Block-List:" gets sent by Github gists, and the header pattern would fail and stop reading the header at that line
Fixes #232
=> Fix http-codec not reading full header when a header has no value

deps/http-codec.lua
Same as https://github.com/luvit/luvit/pull/1052, but for Lit's version of `http-codec`
=> Fix http-codec failing occasionally during chunked decoding

libs/core.lua
Fixes #248, addresses part of #247 
Example output from a completely clean slate (with no existing local lit db):
```
command: make lit://luvit/luvit luvit.exe luvi.exe
load config: C:\Users\Ryan\AppData\Roaming\litconfig
connecting: wss://lit.luvit.io/
fetching: 1 object
fetching: 1 object
fetching: 3 objects
using snapshot: 6e805fb6a48f25304cc6553f18a01ecc30f10e30
creating binary: C:\Users\Ryan\Programming\Luvit\lit\luvit.exe
using luvi from: C:\Users\Ryan\Programming\Luvit\lit\luvi.exe
fetching: 1 object
failed to get snapshot: [string "bundle:libs/codec.lua"]:123: No such hash: 6e805fb6a48f25304cc6553f18a01ecc30f10e30
fetching: 1 object
fetching: 1 object
fetching: 1 object
fetching: 1 object
fetching: 1 object
fetching: 1 object
fetching: 1 object
fetching: 1 object
fetching: 1 …
```
=> Make missing snapshots fall back to resolving deps individually

libs/api.lua
Server-side version of #249 / 5c75c68a0e9836a96e9ba93a881121c4733e0dcf
Fixes #248 and most of #247 without needing the lit client to be updated
---
Also made it enforce that the resolved hash matches the hash in meta.snapshot, which means that its guaranteed that the next time the zip is requested it'll be able to just use the snapshot hash and not need to resolve the deps (since the resolution will create that hash in the db). Not sure if that makes sense to do or not.
=> Make server fall back to resolving deps for missing snapshots when exporting zips

libs/api.lua, libs/calculate-historic-deps.lua
When creating the zip of a missing snapshot, makes the server calc deps by only including deps that are older than the package that is including them. This should usually result in the same hash as the exising snapshot hash.
Fixes #253
EDIT: Note that this currently only works properly if the local db has tags for all of the versions of every dep that should be used--e.g. if you only have newer tags locally then this will fail (see fetch.lua command below for how I was fixing this for local testing). It would be best if `calculate-historic-deps` grabbed any missing versions from the remote before calculating the deps, but for now that's not super necessary (since this is mostly a hotfix). There's a TODO comment in the code for where this could be done.
=> Make server calc missing snapshot deps more consistently

get-lit.ps1, get-lit.sh
Example sh usage:
`curl get-lit.sh | LUVI_VERSION=2.7.6 LIT_VERSION=3.5.4 sh`
Example ps1 usage:
```
set LUVI_VERSION=3.5.4
set LIT_VERSION=2.7.6
PowerShell -NoProfile ...
```
---
Note that it would also be possible to specify the Luvit version (to do something like `lit make lit://luvit/luvit@2.11.2`), but due to how the Lit version matching works, this will match `2.x.x` so it wouldn't really be useful (i.e. it would install `2.15.0` even if you specify `2.11.2`).
=> get-lit: Allow specifiying the lit/luvi versions to download

libs/core.lua, libs/export-zip.lua
Lit currently bundles compiled .lua files if their bytecode is smaller in size than the original source file. I propose that we change this.
**Issue 1:** The attempt at space saving is negligible or detrimental.
Using lit itself as an example of a bundled luvi 2.9.3 app on Windows, the resulting file sizes are:
No compilation: 4,123 KB
Partial compilation (current behavior): 4,144 KB
Full compilation: 4,148 KB
While there is sometimes a reduction in individual .lua file sizes, there is actually an overall increase in total executable size here. Presumably bytecode is being zipped with less efficiency than the source? Additionally, luvi contributes over 90% of the executable size here, so there isn't much room for space negotiation.
**Issue 2:** Lua compiled using one luvi version may be …
=> Disable lua compilation based on file size

deps/http-codec.lua, get-lit.ps1, get-lit.sh, package.lua
Note that, as of now, the latest version of `creationix/coro-fs` has not been published (https://github.com/luvit/lit/pull/260). Because it's not in the `luvit/` namespace, I believe only @creationix can do that. Might be worth waiting for that to be published before merging this.
Closes #265
=> Bump deps / Luvi / Lit versions

commands/serve.lua, libs/api.lua, libs/db-cached.lua
Should help with https://github.com/luvit/luvit.io/issues/24
There are two parts to this:
- The API was already caching the `hash -> meta` part of the `author/name/version -> hash -> meta` lookup, but this cache was not being warmed on start, so the first request would take roughly twice as long as future requests.
+ Warming the cache in advance also required a change to how urls were cached, since its technically possible for `prefix` to change between requests, so we can't use the same cached url every time
- All db lookups would access the file system every time, meaning that all `/search/` endpoint requests would iterate all refs, read them, etc for general searches i.e. `/search/*`. The actual values very rarely change, though, and the amount of memory needed to cache all those …
=> api: Do more caching to speed up search responses

get-lit.ps1
If there was an older lit.exe or luvi.exe on your PATH, then running get-lit.ps1 anywhere would use those older existing lit.exe/luvi.exe instead of the newly downloaded ones. This could lead to 'cannot load incompatible bytecode' errors that should no longer be possible after #263.
=> get-lit.ps1: Specify the current directory when starting luvi.exe/lit.exe

deps/secure-socket/context.lua
The fix in #257 makes DEFAULT_SECUREPROTOCOL `TLS` on OpenSSL 1.1.0, which does not support it (it correctly does this for OpenSSL < 1.1.0 and OpenSSL > 1.1.0). This specific OpenSSL version does not accept `TLS` and should instead use `SSLv23` like previous versions.
This issue keeps coming up with people using Luvi 2.9.1 (the affected luvi).
=> Fix secure-socket for OpenSSL 1.1.0

deps/coro-channel.lua, deps/coro-fs.lua, deps/coro-net.lua, deps/coro-spawn.lua, deps/coro-split.lua, deps/prompt.lua, deps/secure-socket/init.lua, deps/secure-socket/package.lua
Closes #273. 
I replaced every `assert(coroutine.resume(thread, ...))` with an `assertResume(thread, ...)` wrapper defined in each file that needs it. Not really a sustainable solution, but I didn't want to make a new dependency at this time.
=> Preserves tracebacks  for coroutine resumes

libs/core.lua
=> Assert pkey.read for better error messages when failing to parse privateKey file

deps/coro-fs.lua
This was causing the sync version to be called in libuv and the callback get ignored so the coroutine would never return.
=> Fix missing flags for fs.symlink

deps/coro-fs.lua
`flags` is still valid, though it isn't that accurate.
Thanks for your time, and sorry for the useless PRs 😬
=> correcting fs.access parameter name

deps/coro-http.lua
Since `coro_net.createServer` already exposes the server handle, wouldn't also make sense to do that on the `coro-http` side? So stuff such as closing the server (for example) can be done.
=> coro-http: createServer: exposing the server handle

deps/coro-http.lua, deps/coro-net.lua, deps/coro-websocket.lua, deps/weblit-server.lua, libs/rdb.lua, package.lua
http-codec is a stateful parser and this wasn't really supported properly.
Before this patch, coro-net would reuse the exact same stateful parser
for all concurrent and future streams which has many issues.
This was probably the cause of many bugs including the one that makes
the production website hang whenever a request triggers http raw body mode.
This PR updates coro-net to now support both statefull and stateless codecs
and updates coro-http, coro-websocket and others to use the new feature.
Third-party libraries that use coro-net directly with http-codec will need
a similar update.
=> Add proper stateful codec support to coro-net.

deps/coro-channel.lua, deps/coro-http.lua, deps/weblit-app.lua
A simple server to reproduce this is:
```lua
require('coro-http').createServer("127.0.0.1", 8080, function(req)
p(req)
return {
code = 200,
reason = "OK",
{"Content-Length", "6"},
-- Also test with this uncommented, but it should work with both.
-- {"Connection", "close"},
}, "hello\n"
end)
p 'http://localhost:8080/'
```
In another terminal, watch the sockets:
```sh
while true; do clear && netstat -an | grep 8080 && sleep 1; done
```
Initially you should only the listening socket:
```
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN     
```
And in another, hit the server using curl:
```sh
curl -v http://localhost:8080/test
```
When you have `Connection: closed` commented out, curl should report the server supports http keepalive:
```
...
* Connection #0 to host …
```
=> Fix coro-http server to close the socket when done

deps/coro-split.lua
**Issue:**
If you try the following code
```lua
require'coro-split'(
function()
print(1)
print(2)
end,
function()
print(3)
print(4)
end,
function()
print(5)
print(6)
end
)
```
it would error with the said error message after it executed everything successfully
```
cannot resume running coroutine
```
**Explanation:**
That's due to all tasks being spawned and completed before `coroutine.yield` have been reached, therefor the `coroutine.resume` in `check` would fail.
**Solution:**
Basically make sure you only resume if yield have been executed (or tagged as so), otherwise return without yielding.
=> coro-split: fixing coroutine resume before yielding

deps/http-codec.lua
This will also need a version bump and subsequent bump in `creationix/http-codec`.
The original code here did not properly account for chunked encoding extensions, which may be present but should be ignored.
As stated in [RFC 7230 Section 4.1](https://datatracker.ietf.org/doc/html/rfc7230#section-4.1):
```
chunk          = chunk-size [ chunk-ext ] CRLF
chunk-data CRLF
chunk-ext      = *( ";" chunk-ext-name [ "=" chunk-ext-val ] )
chunk-ext-name = token
chunk-ext-val  = token / quoted-string
```
The code used to verify the bug in the original and verify that this fixes it is:
```lua
local codec = require 'http-codec'
local payload = ([[
HTTP/1.1 200 OK
Transfer-Encoding: chunked
4; some_really_long_extension=true
test
0
]]):gsub('\n', '\r\n')
local decoder = codec.decoder()
local _, index …
```
=> handle chunked encoding extensions in chunk header

deps/http-codec.lua
This passed through my test case. decodeChunked should return early if it does not have enough data to process.
=> amendment: #305: fix missing return in decodeChunked when chunk header is missing

deps/secure-socket/biowrap.lua
This removes the assumption that the unverified cert is the first in the chain, if additional certs are supplied this reports an error message that looks like `Error verifying peer: ok`.
Before the changes: 
After the changes:
This might still be ambiguous to the user although, as in, the browser could still be able to access a said website -since the main cert is valid- but coro-net for example could not access it because one of the additional certs is invalid. Perhaps we can somehow report which cert is exactly unverified?
=> secure-socket: more accurate error messages

deps/coro-net.lua
Coro-net creates a new handle (whether tcp socket or a pipe) then proceeds to try connecting it. The code handling the connection failure does not seem to free the recently opened handle leading to a leak happening on `socket:connect` failures.
For ease of testing, I simulated a network error by simply commenting out `uv.getaddrinfo` and forcing it to connect to a non-existence host / port, forcing a `ECONNREFUSED` error like so:
```lua
options.isTcp = true
if options.isTcp then
local res = {{addr = '127.0.0.1', port = 8000}}
if not res then return nil, err end
socket = uv.new_tcp()
socket:connect(res[1].addr, res[1].port, makeCallback(options.timeout))
...
```
The results of doing multiple `coro_net.connect` calls with this simulation resulted in the following:
With this patch it seems …
=> coro-net: fix handle leak when connect errors

get-lit.ps1, get-lit.sh
This also workaround a mis-labled Luvi tag, v2.12.0 is in fact Luvi version `2.11.0-21` which causes an error with Lit's `core.getLuvi` not finding a tag for `2.12.0-21`.
=> get-lit: update luvi to 2.14.0

deps/secure-socket/biowrap.lua, deps/secure-socket/init.lua, tests/test-coro-http-security.lua
After secure-socket verifies a certificates and deems it to be valid, it does not check whether this certificate is actually provided by the same server that claims to be the owner of the certificate.  This results in a possible attack vector where an attacker that is intercepting a connection (through a MITM attack) to provide any valid SSL certificate (for example, one they made themselves for a domain they own) and secure-socket (and by extension, coro-net/coro-http etc) would accept that certificate.
1. A connection is intercepted by an attacker between `google.com` and a user-agent using secure-socket.
2. The attacker provides their valid certificate for the domain they own `doodle.com`.
3. secure-socket will check for the validity of the certificate (which it is valid), and start …
=> fix: secure-socket does not check for certificate domain

deps/secure-socket/package.lua
Includes:
- https://github.com/luvit/lit/pull/296: fixes error messages on invalid certificates.
- https://github.com/luvit/lit/pull/326: adds identity checks to properly secure connections.
@squeek502 / @truemedian  A new Lit release would be appreciated
=> secuer-socket: patch version bump

deps/coro-channel.lua, tests/test-coro-channel.lua
Consider the following minimal-reproduction code:
```lua
local ssocket = {
-- will finish the write instantly
write = function(self, chunk, callback)
callback()
return true
end,
-- irrelevant, just to make the example work
is_closing = function()
return true
end 
}
local write = require("coro-channel").wrapWrite(ssocket)
write("") -- it is important to provide any value here, because a nil value will close the socket instead of attempting a write
```
This will produce the following error
```
ncaught exception:
cannot resume running coroutine
stack traceback:
/home/bilal/deps/coro-channel.lua:16: in function 'assertResume'
/home/bilal/deps/coro-channel.lua:126: in function 'callback'
/home/bilal/test.lua:5: in function 'write'
/home/bilal/deps/coro-channel.lua:148: in function 'write' …
```
=> fix: coro-channel attempts to resume running thread

main.lua
We have been calling `uv.run()` from inside of a
libuv callback, which is not allowed. This moves
the original call to `uv.run()` inside of the main xpcall, which is where it is necessary.
This allows the first call to `uv.run()` to be
completely finished before we attempt to exit and
call `uv.run()` again.
=> fix: invalid usage of uv.run() in command runner

deps/readline.lua
Is there a reason this isn't already the case? Apparently some systems will use a line feed (`\010`) instead of a carriage return (`\013`).  
Not handling line feed on those systems results in a "Unhandled Key" error when enter is pressed.
On Linux when an enter is pressed apparently line feed ('\010") is used (which makes sense) but on most systems an stty option `onlcr` automatically converts that into a carriage return, which is why readline doesn't fail on those systems.  Seems like when this `onlcr` option is not enabled readline will fail although.
This was reported as a question over on the [Discord server ](https://discord.com/channels/377572091869790210/377966865999462408/1229037907969441895) by @Be1zebub.
=> readline: also handle line feed for Enter

commands/update.lua, deps/coro-channel.lua, deps/coro-http.lua, deps/coro-split.lua, deps/http-codec.lua, deps/readline.lua, deps/weblit-auto-headers.lua, deps/weblit-server.lua, deps/websocket-codec.lua, libs/api.lua, libs/autoconfig.lua, libs/core.lua, libs/db-fs.lua, libs/export-zip.lua, libs/handlers.lua, libs/import.lua, libs/pkg.lua, libs/rules.lua, libs/stats.lua, luvit-loader.lua, main.lua, tests/main.lua
Now bringing luajit-independence to lit. It was mostly used to check if the os was windows or not. Other os-level checks have been replaced with luv.os_uname()
For support with Lua 5.4, `loadstring` has been replaced with a selection between `loadstring` and `load`, whichever is available. The same has happened with `unpack` and `table.unpack`.
luvit-loader now supports injecting a searcher instead of a loader.
I have tested that this works with a Lua Luvi 2.15.0 to `lit make` luvit.
=> Version compat

package.lua
There have a been a lot of changes and years since 3.8.5 (9b0f3be64e9b8dd65bece121ce9a2ae8d8ac1c00 and 84fc5d729f1088b3b93bc9a55d1f7a245bca861d). I think it's time we update to the current luvi and give lit a minor bump. `get-lit` changes will follow.
=> Bump lit to 3.9.0 and luvi to 2.15.0

deps/sha1/init.lua
There seems to be a slight mistake in the SHA1 library where `floor` was incorrectly assigned as `table.floor` which isn't a thing...
TL;DR: A runtime error.
Just to make sure I wasn't losing my brain, I checked usages of `floor` in the file to confirm that they align with actual mathematical use and not any kind of magical table operations.
But anyways yeah, just a `table.floor` -> `math.floor`.
=> SHA1: `table.floor` -> `math.floor`

deps/resource.lua
This was missed during the original adoption. This was the only package already under `luvit/` so that the bulk publish for the new dependencies was not applied here because the version already existed.
After this is merged `luvit/resource` needs to be published on lit.
=> adoption: bump luvit/resource to 2.1.1 for re-release

commands/init.lua
fixes #340 by adding a confirmation prompt when the output file already exists.
while at it, I also fixed the annoying indention that is outputted by the command.
=> add overwrite confirmation for init
