commands/README
commands/update.lua
deps/auto-updater.lua
libs/auto-updater.lua
libs/autocore.lua
libs/core.lua

For now it simply notifies the user there is an update and has a new command the user needs to run to start the update.

WIP: Self Updating Lit

---

README.md

* Adds link to the main REST API for convenience
* Fixes obsolete link to `lib` directory

Improve README a bit

---

deps/coro-http.lua

302 is followed already, but 307 should also be followed.

307 is also a redirect and should be followed automatically

---

commands/update.lua

RFR: Rewrite update system

---

get-lit.ps1

fix(get-lit.ps1): Detect and work with 32bit archs on windows

---

commands/README
commands/init.lua

I think I have got this down now. I'll explain some features:
* create either package.lua or init.lua
* defaults to your own username
* defaults to your own author details
This is my first PR that is Lua based, so let me know what needs to be fixed or changed before going ahead.

Init command. Closes #124

---

libs/auto-updater.lua

The `action` variable is now a table with 2 words for each case.
Does this work?

Action names

---

commands/init.lua

init: Fix ordering of parameters in package metadata

---

libs/core.lua

Pass `luvi_source` to all handler functions. This allows us to use a custom luvi binary also for all URL handlers.

libs/core: fix luvi_source

---

get-lit.ps1
get-lit.sh

Bump lit version in get-lit scripts

---

deps/websocket-codec.lua

Discovered in #210. Version bump at your discretion.

Fixes WebSocket decoder chunk length check

---

deps/coro-channel.lua

Adds shutdown check to coro-channel close

---

README.md

- Closes #234 
luvit/lit#234
luvit/luvit#1026

Update PowerShell command to use TLS 1.2

---

get-lit.ps1

script can now choose tls11 tls12

updated so script should work

---

main.lua

When running lit on macOS, I noticed a problem where output was being truncated:
```
$ luvi . -- --help
lit version: 3.6.0
luvi version: v2.7.6
command: --help
Lit CLI Commands
================
lit help                    Show usage information.
lit version                 Show just the lit version.
lit update                  Update lit to the latest version.
lit make appdir             Build appdir into a single executable.
lit serve prefix            Start a lit package server (upstream or proxy).
`prefix` is the protocol and host.
EG: lit serve https://lit.luvit.io
Local configuration
-------------------
lit auth username           Verify local private key and set username.
lit up [url]                Go online.  Uses default upstream or url.
lit down                    Go offline …
```

Cleanup handles properly on exit;

---

libs/api.lua
libs/calculate-historic-deps.lua

Forgot to actually update api.lua to pass the tag date to calculateHistoricDeps. Whoops.
Actually fixes #253

Fix #254 not being fully implemented

---

deps/secure-socket/context.lua

Fixes #256
Lit version of https://github.com/luvit/luvit/pull/1062
Tested and confirmed to work with both OpenSSL 1.0.2 and 1.1.1

Fix secure-socket for OpenSSL > 1.1.0

---

deps/http-codec.lua

See luvit/luvit@c3dd9cee282f152bcb7a9325d6ea733338d2faf8

Fixes parsing of HTTP response status

---

deps/coro-http.lua

*Continuation of https://github.com/luvit/lit/pull/230*
coro-http currently does not have the functionality to prevent following redirects.
This PR adds an `options` argument to the request function, which is a table of possible options for the request
This also replaces the `timeout` argument, which has now been moved into the `options` table, making it look like:
```
options
timeout (number) - Default: nil
followRedirects (boolean) - Default: true
```
This also allows more options to be added over time as required.
For backwards compatibility, if a `number` is provided instead of a table to the options parameter, it is assumed as the timeout.

Add options table to coro-http request

---

commands/init.lua

.gitconfig lines can end in \r

add \r to getConfig ini match

---

README.md

Bit of a pet peeve of mine when information like this is left unsaid, so I thought I'd fix that.

Add 'Development' section to the readme with some useful advice

---

deps/websocket-codec.lua

Update amount of bytes used in Sec-WebSocket-Key header https://datatracker.ietf.org/doc/html/rfc6455#section-4.2.1

RFC 6455 Sec-WebSocket-Key
